// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RBAT.Core;

namespace RBAT.Core.Migrations.RBAT
{
    [DbContext(typeof(RBATContext))]
    [Migration("20191212021543_AddedRatedPower")]
    partial class AddedRatedPower
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RBAT.Core.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("ApportionmentFlowTarget");

                    b.Property<int>("ChannelTypeId");

                    b.Property<double?>("ConstantHeadWaterLevel");

                    b.Property<double?>("ConstantTailWaterLevel");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int?>("DownstreamChannelTailWaterElevationID");

                    b.Property<int?>("DownstreamNodeID");

                    b.Property<int?>("DownstreamReservoirTailWaterElevationID");

                    b.Property<string>("MapData")
                        .HasColumnType("text");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("NumberOfRoutingPhases");

                    b.Property<double?>("OverallHydroPowerPlantEfficiency");

                    b.Property<double?>("PercentReturnFlow");

                    b.Property<double?>("RatedPower");

                    b.Property<int?>("RecordedFlowStationID");

                    b.Property<int?>("ReferenceNodeID");

                    b.Property<double?>("RoutingCoefficientA");

                    b.Property<double?>("RoutingCoefficientN");

                    b.Property<bool>("RoutingOptionUse");

                    b.Property<double?>("TotalLicensedVolume");

                    b.Property<int?>("UpstreamChannelHeadWaterElevationID");

                    b.Property<int?>("UpstreamChannelWithControlStructureID");

                    b.Property<int?>("UpstreamNodeID");

                    b.Property<int?>("UpstreamNodeWithControlStructureID");

                    b.Property<int?>("UpstreamReservoirHeadWaterElevationID");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelTypeId");

                    b.HasIndex("DownstreamChannelTailWaterElevationID");

                    b.HasIndex("DownstreamNodeID");

                    b.HasIndex("DownstreamReservoirTailWaterElevationID");

                    b.HasIndex("RecordedFlowStationID");

                    b.HasIndex("ReferenceNodeID");

                    b.HasIndex("UpstreamChannelHeadWaterElevationID");

                    b.HasIndex("UpstreamChannelWithControlStructureID");

                    b.HasIndex("UpstreamNodeID");

                    b.HasIndex("UpstreamNodeWithControlStructureID");

                    b.HasIndex("UpstreamReservoirHeadWaterElevationID");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelOptimalSolutions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelID");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ProjectID");

                    b.Property<long>("ScenarioID");

                    b.Property<string>("ScenarioName");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("ScenarioID");

                    b.ToTable("ChannelOptimalSolutions");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelOptimalSolutionsData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ChannelOptimalSolutionsID");

                    b.Property<DateTime>("Created");

                    b.Property<double?>("IdealValue");

                    b.Property<DateTime>("Modified");

                    b.Property<double?>("OptimalValue");

                    b.Property<DateTime>("SurveyDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelOptimalSolutionsID");

                    b.ToTable("ChannelOptimalSolutionsData");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelOutflowCapacity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelID");

                    b.Property<DateTime>("Created");

                    b.Property<double>("Elevation");

                    b.Property<double>("MaximumOutflow");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelID");

                    b.ToTable("ChannelOutflowCapacity");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelPolicyGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelTypeID");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumberOfZonesAboveIdealLevel");

                    b.Property<int>("NumberOfZonesBelowIdealLevel");

                    b.Property<long>("ScenarioID");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("ZoneWeightsOffset");

                    b.HasKey("Id");

                    b.HasIndex("ChannelTypeID");

                    b.HasIndex("ScenarioID");

                    b.ToTable("ChannelPolicyGroup");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelPolicyGroupChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelID");

                    b.Property<long>("ChannelPolicyGroupID");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("Priority");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelID");

                    b.HasIndex("ChannelPolicyGroupID");

                    b.ToTable("ChannelPolicyGroupChannel");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelTravelTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelID");

                    b.Property<DateTime>("Created");

                    b.Property<double>("Flow");

                    b.Property<DateTime>("Modified");

                    b.Property<double>("TravelTime");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelID");

                    b.ToTable("ChannelTravelTime");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ChannelType");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelZoneLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelID");

                    b.Property<long>("ChannelPolicyGroupID");

                    b.Property<DateTime>("Created");

                    b.Property<double?>("IdealZone");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("Year");

                    b.Property<double?>("ZoneAboveIdeal1");

                    b.Property<double?>("ZoneAboveIdeal2");

                    b.Property<double?>("ZoneAboveIdeal3");

                    b.Property<double?>("ZoneAboveIdeal4");

                    b.Property<double?>("ZoneAboveIdeal5");

                    b.Property<double?>("ZoneAboveIdeal6");

                    b.Property<double?>("ZoneBelowIdeal1");

                    b.Property<double?>("ZoneBelowIdeal10");

                    b.Property<double?>("ZoneBelowIdeal2");

                    b.Property<double?>("ZoneBelowIdeal3");

                    b.Property<double?>("ZoneBelowIdeal4");

                    b.Property<double?>("ZoneBelowIdeal5");

                    b.Property<double?>("ZoneBelowIdeal6");

                    b.Property<double?>("ZoneBelowIdeal7");

                    b.Property<double?>("ZoneBelowIdeal8");

                    b.Property<double?>("ZoneBelowIdeal9");

                    b.HasKey("Id");

                    b.HasIndex("ChannelID");

                    b.HasIndex("ChannelPolicyGroupID");

                    b.ToTable("ChannelZoneLevel");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelZoneWeight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ChannelPolicyGroupID");

                    b.Property<DateTime>("Created");

                    b.Property<double?>("IdealZone");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("ZoneAboveIdeal1");

                    b.Property<double?>("ZoneAboveIdeal2");

                    b.Property<double?>("ZoneAboveIdeal3");

                    b.Property<double?>("ZoneAboveIdeal4");

                    b.Property<double?>("ZoneAboveIdeal5");

                    b.Property<double?>("ZoneAboveIdeal6");

                    b.Property<double?>("ZoneBelowIdeal1");

                    b.Property<double?>("ZoneBelowIdeal10");

                    b.Property<double?>("ZoneBelowIdeal2");

                    b.Property<double?>("ZoneBelowIdeal3");

                    b.Property<double?>("ZoneBelowIdeal4");

                    b.Property<double?>("ZoneBelowIdeal5");

                    b.Property<double?>("ZoneBelowIdeal6");

                    b.Property<double?>("ZoneBelowIdeal7");

                    b.Property<double?>("ZoneBelowIdeal8");

                    b.Property<double?>("ZoneBelowIdeal9");

                    b.HasKey("Id");

                    b.HasIndex("ChannelPolicyGroupID");

                    b.ToTable("ChannelZoneWeight");
                });

            modelBuilder.Entity("RBAT.Core.Models.ClimateStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Altitude");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("EpType");

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("ClimateStation");
                });

            modelBuilder.Entity("RBAT.Core.Models.CustomTimeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<decimal>("Length");

                    b.Property<DateTime>("Modified");

                    b.Property<long>("ScenarioId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("CustomTimeStep");
                });

            modelBuilder.Entity("RBAT.Core.Models.MeasuringUnit", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MeasuringUnit");
                });

            modelBuilder.Entity("RBAT.Core.Models.NetEvaporation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdjustmentFactor");

                    b.Property<int>("ClimateStationID");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ClimateStationID");

                    b.HasIndex("NodeID");

                    b.ToTable("NetEvaporation");
                });

            modelBuilder.Entity("RBAT.Core.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<decimal?>("LandUseFactor");

                    b.Property<string>("MapData")
                        .HasColumnType("text");

                    b.Property<int?>("MeasuringUnitId");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NodeTypeId");

                    b.Property<decimal?>("SizeOfIrrigatedArea");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("MeasuringUnitId");

                    b.HasIndex("NodeTypeId");

                    b.ToTable("Node");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeOptimalSolutions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsNetEvaporation");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<int>("ProjectID");

                    b.Property<long>("ScenarioID");

                    b.Property<string>("ScenarioName");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("ScenarioID");

                    b.ToTable("NodeOptimalSolutions");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeOptimalSolutionsData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<double?>("IdealValue");

                    b.Property<DateTime>("Modified");

                    b.Property<long>("NodeOptimalSolutionsID");

                    b.Property<double?>("OptimalValue");

                    b.Property<DateTime>("SurveyDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NodeOptimalSolutionsID");

                    b.ToTable("NodeOptimalSolutionsData");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodePolicyGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CopyNodeLevelasFirstComponent");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("EndTimeStep");

                    b.Property<bool>("EqualDeficits");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NodeTypeID");

                    b.Property<int>("NumberOfZonesAboveIdealLevel");

                    b.Property<int>("NumberOfZonesBelowIdealLevel");

                    b.Property<long>("ScenarioID");

                    b.Property<int?>("StartTimeStep");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("ZoneWeightsOffset");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeID");

                    b.HasIndex("ScenarioID");

                    b.ToTable("NodePolicyGroup");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodePolicyGroupNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<long>("NodePolicyGroupID");

                    b.Property<int>("Priority");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.HasIndex("NodePolicyGroupID");

                    b.ToTable("NodePolicyGroupNode");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("NodeType");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeZoneLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<long>("NodePolicyGroupID");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("Year");

                    b.Property<double?>("ZoneAboveIdeal1");

                    b.Property<double?>("ZoneAboveIdeal2");

                    b.Property<double?>("ZoneAboveIdeal3");

                    b.Property<double?>("ZoneAboveIdeal4");

                    b.Property<double?>("ZoneAboveIdeal5");

                    b.Property<double?>("ZoneAboveIdeal6");

                    b.Property<double?>("ZoneBelowIdeal1");

                    b.Property<double?>("ZoneBelowIdeal10");

                    b.Property<double?>("ZoneBelowIdeal2");

                    b.Property<double?>("ZoneBelowIdeal3");

                    b.Property<double?>("ZoneBelowIdeal4");

                    b.Property<double?>("ZoneBelowIdeal5");

                    b.Property<double?>("ZoneBelowIdeal6");

                    b.Property<double?>("ZoneBelowIdeal7");

                    b.Property<double?>("ZoneBelowIdeal8");

                    b.Property<double?>("ZoneBelowIdeal9");

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.HasIndex("NodePolicyGroupID");

                    b.ToTable("NodeZoneLevel");
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeZoneWeight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<long>("NodePolicyGroupID");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("ZoneAboveIdeal1");

                    b.Property<double?>("ZoneAboveIdeal2");

                    b.Property<double?>("ZoneAboveIdeal3");

                    b.Property<double?>("ZoneAboveIdeal4");

                    b.Property<double?>("ZoneAboveIdeal5");

                    b.Property<double?>("ZoneAboveIdeal6");

                    b.Property<double?>("ZoneBelowIdeal1");

                    b.Property<double?>("ZoneBelowIdeal10");

                    b.Property<double?>("ZoneBelowIdeal2");

                    b.Property<double?>("ZoneBelowIdeal3");

                    b.Property<double?>("ZoneBelowIdeal4");

                    b.Property<double?>("ZoneBelowIdeal5");

                    b.Property<double?>("ZoneBelowIdeal6");

                    b.Property<double?>("ZoneBelowIdeal7");

                    b.Property<double?>("ZoneBelowIdeal8");

                    b.Property<double?>("ZoneBelowIdeal9");

                    b.HasKey("Id");

                    b.HasIndex("NodePolicyGroupID");

                    b.ToTable("NodeZoneWeight");
                });

            modelBuilder.Entity("RBAT.Core.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CalculationBegins");

                    b.Property<DateTime>("CalculationEnds");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DataStepTypeID");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("MapData");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("RoutingOptionTypeID");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DataStepTypeID");

                    b.HasIndex("RoutingOptionTypeID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("RBAT.Core.Models.ProjectChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ProjectId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectChannel");
                });

            modelBuilder.Entity("RBAT.Core.Models.ProjectNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeId");

                    b.Property<int>("ProjectId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectNode");
                });

            modelBuilder.Entity("RBAT.Core.Models.RecordedFlowStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Altitude");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("RecordedFlowStation");
                });

            modelBuilder.Entity("RBAT.Core.Models.RoutingOptionType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("RoutingOptionType");
                });

            modelBuilder.Entity("RBAT.Core.Models.Scenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CalculationBegins");

                    b.Property<DateTime?>("CalculationEnds");

                    b.Property<DateTime>("Created");

                    b.Property<int?>("DataTimeStepTypeID");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("ProjectID");

                    b.Property<int?>("ScenarioTypeID");

                    b.Property<int?>("TimeStepTypeID");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DataTimeStepTypeID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("ScenarioTypeID");

                    b.HasIndex("TimeStepTypeID");

                    b.ToTable("Scenario");
                });

            modelBuilder.Entity("RBAT.Core.Models.ScenarioType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("ScenarioType");
                });

            modelBuilder.Entity("RBAT.Core.Models.StartingReservoirLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<double>("InitialElevation");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeId");

                    b.Property<long>("ScenarioId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("StartingReservoirLevel");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeClimateData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClimateStationID");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("Value")
                        .HasColumnName("ClimateData");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("ClimateStationID");

                    b.ToTable("TimeClimateData");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeHistoricLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("Value")
                        .HasColumnName("Elevation");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.ToTable("TimeHistoricLevel");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeNaturalFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<int>("ProjectID");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("Value")
                        .HasColumnName("NaturalFlow");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.HasIndex("ProjectID");

                    b.ToTable("TimeNaturalFlow");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeRecordedFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("RecordedFlowStationID");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("Value")
                        .HasColumnName("RecordedFlow");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("RecordedFlowStationID");

                    b.ToTable("TimeRecordedFlow");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeStepType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<bool>("CalculationFlag");

                    b.Property<bool>("DataFlag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TimeStepType");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeStorageCapacity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Area");

                    b.Property<DateTime>("Created");

                    b.Property<double>("Elevation");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<DateTime>("SurveyDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.ToTable("TimeStorageCapacity");
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeWaterUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NodeID");

                    b.Property<int>("TimeComponentType");

                    b.Property<int>("TimeComponentValue");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<double?>("Value")
                        .HasColumnName("WaterUse");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("NodeID");

                    b.ToTable("TimeWaterUse");
                });

            modelBuilder.Entity("RBAT.Core.Models.Channel", b =>
                {
                    b.HasOne("RBAT.Core.Models.ChannelType", "ChannelType")
                        .WithMany()
                        .HasForeignKey("ChannelTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Channel", "DownstreamChannelTailWaterElevation")
                        .WithMany()
                        .HasForeignKey("DownstreamChannelTailWaterElevationID");

                    b.HasOne("RBAT.Core.Models.Node", "DownstreamNode")
                        .WithMany()
                        .HasForeignKey("DownstreamNodeID");

                    b.HasOne("RBAT.Core.Models.Node", "DownstreamReservoirTailWaterElevation")
                        .WithMany()
                        .HasForeignKey("DownstreamReservoirTailWaterElevationID");

                    b.HasOne("RBAT.Core.Models.RecordedFlowStation", "RecordedFlowStation")
                        .WithMany("Channel")
                        .HasForeignKey("RecordedFlowStationID");

                    b.HasOne("RBAT.Core.Models.Node", "ReferenceNode")
                        .WithMany()
                        .HasForeignKey("ReferenceNodeID");

                    b.HasOne("RBAT.Core.Models.Channel", "UpstreamChannelHeadWaterElevation")
                        .WithMany()
                        .HasForeignKey("UpstreamChannelHeadWaterElevationID");

                    b.HasOne("RBAT.Core.Models.Channel", "UpstreamChannelWithControlStructure")
                        .WithMany()
                        .HasForeignKey("UpstreamChannelWithControlStructureID");

                    b.HasOne("RBAT.Core.Models.Node", "UpstreamNode")
                        .WithMany()
                        .HasForeignKey("UpstreamNodeID");

                    b.HasOne("RBAT.Core.Models.Node", "UpstreamNodeWithControlStructure")
                        .WithMany()
                        .HasForeignKey("UpstreamNodeWithControlStructureID");

                    b.HasOne("RBAT.Core.Models.Node", "UpstreamReservoirHeadWaterElevation")
                        .WithMany()
                        .HasForeignKey("UpstreamReservoirHeadWaterElevationID");
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelOptimalSolutions", b =>
                {
                    b.HasOne("RBAT.Core.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelOptimalSolutionsData", b =>
                {
                    b.HasOne("RBAT.Core.Models.ChannelOptimalSolutions", "ChannelOptimalSolutions")
                        .WithMany()
                        .HasForeignKey("ChannelOptimalSolutionsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelOutflowCapacity", b =>
                {
                    b.HasOne("RBAT.Core.Models.Channel", "Channel")
                        .WithMany("ChannelOutflowCapacities")
                        .HasForeignKey("ChannelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelPolicyGroup", b =>
                {
                    b.HasOne("RBAT.Core.Models.ChannelType", "ChannelType")
                        .WithMany()
                        .HasForeignKey("ChannelTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Scenario", "Scenario")
                        .WithMany("ChannelPolicyGroups")
                        .HasForeignKey("ScenarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelPolicyGroupChannel", b =>
                {
                    b.HasOne("RBAT.Core.Models.Channel", "Channel")
                        .WithMany("ChannelPolicyGroupChannels")
                        .HasForeignKey("ChannelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.ChannelPolicyGroup", "ChannelPolicyGroup")
                        .WithMany("ChannelPolicyGroupChannels")
                        .HasForeignKey("ChannelPolicyGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelTravelTime", b =>
                {
                    b.HasOne("RBAT.Core.Models.Channel", "Channel")
                        .WithMany("TravelTimes")
                        .HasForeignKey("ChannelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelZoneLevel", b =>
                {
                    b.HasOne("RBAT.Core.Models.Channel", "Channel")
                        .WithMany("ChannelZoneLevels")
                        .HasForeignKey("ChannelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.ChannelPolicyGroup", "ChannelPolicyGroup")
                        .WithMany("ChannelZoneLevels")
                        .HasForeignKey("ChannelPolicyGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ChannelZoneWeight", b =>
                {
                    b.HasOne("RBAT.Core.Models.ChannelPolicyGroup", "ChannelPolicyGroup")
                        .WithMany("ChannelZoneWeights")
                        .HasForeignKey("ChannelPolicyGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.CustomTimeStep", b =>
                {
                    b.HasOne("RBAT.Core.Models.Scenario", "Scenario")
                        .WithMany("CustomTimeSteps")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NetEvaporation", b =>
                {
                    b.HasOne("RBAT.Core.Models.ClimateStation", "ClimateStation")
                        .WithMany("NetEvaporations")
                        .HasForeignKey("ClimateStationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("NetEvaporations")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.Node", b =>
                {
                    b.HasOne("RBAT.Core.Models.MeasuringUnit", "MeasuringUnit")
                        .WithMany()
                        .HasForeignKey("MeasuringUnitId");

                    b.HasOne("RBAT.Core.Models.NodeType", "NodeType")
                        .WithMany()
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeOptimalSolutions", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeOptimalSolutionsData", b =>
                {
                    b.HasOne("RBAT.Core.Models.NodeOptimalSolutions", "NodeOptimalSolutions")
                        .WithMany()
                        .HasForeignKey("NodeOptimalSolutionsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NodePolicyGroup", b =>
                {
                    b.HasOne("RBAT.Core.Models.NodeType", "NodeType")
                        .WithMany()
                        .HasForeignKey("NodeTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Scenario", "Scenario")
                        .WithMany("NodePolicyGroups")
                        .HasForeignKey("ScenarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NodePolicyGroupNode", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("NodePolicyGroupNodes")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.NodePolicyGroup", "NodePolicyGroup")
                        .WithMany("NodePolicyGroupNodes")
                        .HasForeignKey("NodePolicyGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeZoneLevel", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("NodeZoneLevels")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.NodePolicyGroup", "NodePolicyGroup")
                        .WithMany("NodeZoneLevels")
                        .HasForeignKey("NodePolicyGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.NodeZoneWeight", b =>
                {
                    b.HasOne("RBAT.Core.Models.NodePolicyGroup", "NodePolicyGroup")
                        .WithMany("NodeZoneWeights")
                        .HasForeignKey("NodePolicyGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.Project", b =>
                {
                    b.HasOne("RBAT.Core.Models.TimeStepType", "DataStepType")
                        .WithMany()
                        .HasForeignKey("DataStepTypeID");

                    b.HasOne("RBAT.Core.Models.RoutingOptionType", "RoutingOptionType")
                        .WithMany()
                        .HasForeignKey("RoutingOptionTypeID");
                });

            modelBuilder.Entity("RBAT.Core.Models.ProjectChannel", b =>
                {
                    b.HasOne("RBAT.Core.Models.Channel", "Channel")
                        .WithMany("ProjectChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Project", "Project")
                        .WithMany("ProjectChannels")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.ProjectNode", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("ProjectNodes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Project", "Project")
                        .WithMany("ProjectNodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.Scenario", b =>
                {
                    b.HasOne("RBAT.Core.Models.TimeStepType", "DataTimeStepType")
                        .WithMany()
                        .HasForeignKey("DataTimeStepTypeID");

                    b.HasOne("RBAT.Core.Models.Project", "Project")
                        .WithMany("Scenarios")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.ScenarioType", "ScenarioType")
                        .WithMany()
                        .HasForeignKey("ScenarioTypeID");

                    b.HasOne("RBAT.Core.Models.TimeStepType", "TimeStepType")
                        .WithMany()
                        .HasForeignKey("TimeStepTypeID");
                });

            modelBuilder.Entity("RBAT.Core.Models.StartingReservoirLevel", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Scenario", "Scenario")
                        .WithMany("StartingReservoirLevels")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeClimateData", b =>
                {
                    b.HasOne("RBAT.Core.Models.ClimateStation", "ClimateStation")
                        .WithMany()
                        .HasForeignKey("ClimateStationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeHistoricLevel", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("TimeHistoricLevels")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeNaturalFlow", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("TimeNaturalFlows")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RBAT.Core.Models.Project", "Project")
                        .WithMany("TimeNaturalFlows")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeRecordedFlow", b =>
                {
                    b.HasOne("RBAT.Core.Models.RecordedFlowStation", "RecordedFlowStation")
                        .WithMany("TimeRecordedFlows")
                        .HasForeignKey("RecordedFlowStationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeStorageCapacity", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("TimeStorageCapacities")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RBAT.Core.Models.TimeWaterUse", b =>
                {
                    b.HasOne("RBAT.Core.Models.Node", "Node")
                        .WithMany("TimeWaterUses")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
